name: Release

on:
  push:
    branches: [ master ]

concurrency: release

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: 🚀 [INIT] Clone repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 🚀 [INIT] Compute tag name
        id: compute-tag
        run: |
          echo Computing next tag number
          TAG=$(jq -r '.version' plugin.json)
          echo "tagname=${TAG}" >> $GITHUB_OUTPUT
          echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT

      - name: 🚀 [SET] Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.18"

      - name: 🚀 [BUILD] Build application package
        run: |
          make build

      - name: 🚀 [RELEASE] Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./bin/plugin.tar.gz"
          tag: ${{ steps.compute-tag.outputs.tagname }}
          commit: ${{ steps.compute-tag.outputs.branch }}
